pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('SauceDemo') {
                    bat 'python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('SauceDemo') {
                    bat 'python -m pytest -v -n 2 --html=reports/report.html --self-contained-html --alluredir=allure-results'
                }
            }
        }
    }

    post {
        always {
            echo 'Automation execution completed'
        }

        success {
            echo 'All tests passed'
        }

        failure {
            echo 'Automation tests failed'
        }
    }
}